theme: jekyll-theme-slate
title: [Alone in a crowd; transcribing Cambridge Digital Library together]
description: [A crowd-sourcing project by Cambridge Digital Library undertaken during the University of Cambridge's closure period due to the Coronavirus outbreak in 2020]
show_downloads: [false]
